### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by ollesz** [crashdemons/DisplayItem-Spigot#1]
So im using your displayitem 1.14 plugin and i can't see the enchantments when hovering over the linked item. What am i doing wrong?

**Comment by crashdemons** [comment]
Do you see anything when hovering over it?

If not, there may be some other chat plugin canceling DI's behavior (setting sendmodifiedchatevent to false may help in this specific case).

Also, if you're using ViaVersion or other protocol-plugins to bridge 1.14 and 1.13 (or lower) servers or clients, you will have issues displaying some information in the hover text for some users - this is unavoidable because of internal tag changes between versions.

**Comment by crashdemons** [comment]
I'm closing this issue due to the lack of response, if you are able to provide more information please reopen the issue or open a new issue with all of the relevant details.

Thank you.
